 CREATE TABLE PRODUCT (       

PRODUCT_NO VARCHAR2(12 BYTE),       

PRODUCT_NAME VARCHAR2(60 BYTE),       

PRICE NUMBER,       

EA NUMBER(4) DEFAULT 0,       

MAKER VARCHAR2(60 BYTE));         

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_NO") ENABLE; 

ALTER TABLE "PRODUCT" ADD CONSTRAINT "CHECK_EA" CHECK (ea >= 0) ENABLE;

ALTER TABLE "PRODUCT" ADD CONSTRAINT "CHECK_PRICE" CHECK (price >= 0) ENABLE;

select * from PRODUCT;

